kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: sub-cluster1
subjects:
  - kind: ServiceAccount
    name: sub-cluster1
    namespace: sub-cluster1
roleRef:
  kind: ClusterRole
  name: sub-cluster1
  apiVersion: rbac.authorization.k8s.io/v1alpha1
